/*
 Bootstrap v3.1.1 (http://getbootstrap.com)
 Copyright 2011-2014 Twitter, Inc.
 Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
*/
if("undefined"===typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");
+function(b){b.fn.emulateTransitionEnd=function(e){var f=!1,a=this;b(this).one(b.support.transition.end,function(){f=!0});setTimeout(function(){f||b(a).trigger(b.support.transition.end)},e);return this};b(function(){var e=b.support;a:{var f=document.createElement("bootstrap");var a={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},c;for(c in a)if(void 0!==f.style[c]){f={end:a[c]};break a}f=!1}e.transition=
f})}(jQuery);
+function(b){var e=function(a){b(a).on("click",'[data-dismiss="alert"]',this.close)};e.prototype.close=function(a){function c(){e.trigger("closed.bs.alert").remove()}var d=b(this),g=d.attr("data-target");g||(g=(g=d.attr("href"))&&g.replace(/.*(?=#[^\s]*$)/,""));var e=b(g);a&&a.preventDefault();e.length||(e=d.hasClass("alert")?d:d.parent());e.trigger(a=b.Event("close.bs.alert"));a.isDefaultPrevented()||(e.removeClass("in"),b.support.transition&&e.hasClass("fade")?e.one(b.support.transition.end,c).emulateTransitionEnd(150):
c())};var f=b.fn.alert;b.fn.alert=function(a){return this.each(function(){var c=b(this),d=c.data("bs.alert");d||c.data("bs.alert",d=new e(this));"string"==typeof a&&d[a].call(c)})};b.fn.alert.Constructor=e;b.fn.alert.noConflict=function(){b.fn.alert=f;return this};b(document).on("click.bs.alert.data-api",'[data-dismiss="alert"]',e.prototype.close)}(jQuery);
+function(b){var e=function(a,c){this.$element=b(a);this.options=b.extend({},e.DEFAULTS,c);this.isLoading=!1};e.DEFAULTS={loadingText:"loading..."};e.prototype.setState=function(a){var c=this.$element,d=c.is("input")?"val":"html",g=c.data();a+="Text";g.resetText||c.data("resetText",c[d]());c[d](g[a]||this.options[a]);setTimeout(b.proxy(function(){"loadingText"==a?(this.isLoading=!0,c.addClass("disabled").attr("disabled","disabled")):this.isLoading&&(this.isLoading=!1,c.removeClass("disabled").removeAttr("disabled"))},
this),0)};e.prototype.toggle=function(){var a=!0,b=this.$element.closest('[data-toggle="buttons"]');if(b.length){var d=this.$element.find("input");"radio"==d.prop("type")&&(d.prop("checked")&&this.$element.hasClass("active")?a=!1:b.find(".active").removeClass("active"));a&&d.prop("checked",!this.$element.hasClass("active")).trigger("change")}a&&this.$element.toggleClass("active")};var f=b.fn.button;b.fn.button=function(a){return this.each(function(){var c=b(this),d=c.data("bs.button"),g="object"==
typeof a&&a;d||c.data("bs.button",d=new e(this,g));"toggle"==a?d.toggle():a&&d.setState(a)})};b.fn.button.Constructor=e;b.fn.button.noConflict=function(){b.fn.button=f;return this};b(document).on("click.bs.button.data-api","[data-toggle^=button]",function(a){var c=b(a.target);c.hasClass("btn")||(c=c.closest(".btn"));c.button("toggle");a.preventDefault()})}(jQuery);
+function(b){var e=function(a,c){this.$element=b(a);this.$indicators=this.$element.find(".carousel-indicators");this.options=c;this.paused=this.sliding=this.interval=this.$active=this.$items=null;"hover"==this.options.pause&&this.$element.on("mouseenter",b.proxy(this.pause,this)).on("mouseleave",b.proxy(this.cycle,this))};e.DEFAULTS={interval:5E3,pause:"hover",wrap:!0};e.prototype.cycle=function(a){a||(this.paused=!1);this.interval&&clearInterval(this.interval);this.options.interval&&!this.paused&&
(this.interval=setInterval(b.proxy(this.next,this),this.options.interval));return this};e.prototype.getActiveIndex=function(){this.$active=this.$element.find(".item.active");this.$items=this.$active.parent().children();return this.$items.index(this.$active)};e.prototype.to=function(a){var c=this,d=this.getActiveIndex();if(!(a>this.$items.length-1||0>a))return this.sliding?this.$element.one("slid.bs.carousel",function(){c.to(a)}):d==a?this.pause().cycle():this.slide(a>d?"next":"prev",b(this.$items[a]))};
e.prototype.pause=function(a){a||(this.paused=!0);this.$element.find(".next, .prev").length&&b.support.transition&&(this.$element.trigger(b.support.transition.end),this.cycle(!0));this.interval=clearInterval(this.interval);return this};e.prototype.next=function(){if(!this.sliding)return this.slide("next")};e.prototype.prev=function(){if(!this.sliding)return this.slide("prev")};e.prototype.slide=function(a,c){var d=this.$element.find(".item.active"),g=c||d[a](),e=this.interval,h="next"==a?"left":"right",
f="next"==a?"first":"last",l=this;if(!g.length){if(!this.options.wrap)return;g=this.$element.find(".item")[f]()}if(g.hasClass("active"))return this.sliding=!1;f=b.Event("slide.bs.carousel",{relatedTarget:g[0],direction:h});this.$element.trigger(f);if(!f.isDefaultPrevented())return this.sliding=!0,e&&this.pause(),this.$indicators.length&&(this.$indicators.find(".active").removeClass("active"),this.$element.one("slid.bs.carousel",function(){var a=b(l.$indicators.children()[l.getActiveIndex()]);a&&a.addClass("active")})),
b.support.transition&&this.$element.hasClass("slide")?(g.addClass(a),g[0].offsetWidth,d.addClass(h),g.addClass(h),d.one(b.support.transition.end,function(){g.removeClass([a,h].join(" ")).addClass("active");d.removeClass(["active",h].join(" "));l.sliding=!1;setTimeout(function(){l.$element.trigger("slid.bs.carousel")},0)}).emulateTransitionEnd(1E3*d.css("transition-duration").slice(0,-1))):(d.removeClass("active"),g.addClass("active"),this.sliding=!1,this.$element.trigger("slid.bs.carousel")),e&&this.cycle(),
this};var f=b.fn.carousel;b.fn.carousel=function(a){return this.each(function(){var c=b(this),d=c.data("bs.carousel"),g=b.extend({},e.DEFAULTS,c.data(),"object"==typeof a&&a),m="string"==typeof a?a:g.slide;d||c.data("bs.carousel",d=new e(this,g));if("number"==typeof a)d.to(a);else if(m)d[m]();else g.interval&&d.pause().cycle()})};b.fn.carousel.Constructor=e;b.fn.carousel.noConflict=function(){b.fn.carousel=f;return this};b(document).on("click.bs.carousel.data-api","[data-slide], [data-slide-to]",
function(a){var c=b(this),d,g=b(c.attr("data-target")||(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,""));d=b.extend({},g.data(),c.data());var e=c.attr("data-slide-to");e&&(d.interval=!1);g.carousel(d);(e=c.attr("data-slide-to"))&&g.data("bs.carousel").to(e);a.preventDefault()});b(window).on("load",function(){b('[data-ride="carousel"]').each(function(){var a=b(this);a.carousel(a.data())})})}(jQuery);
+function(b){var e=function(a,c){this.$element=b(a);this.options=b.extend({},e.DEFAULTS,c);this.transitioning=null;this.options.parent&&(this.$parent=b(this.options.parent));this.options.toggle&&this.toggle()};e.DEFAULTS={toggle:!0};e.prototype.dimension=function(){return this.$element.hasClass("width")?"width":"height"};e.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var a=b.Event("show.bs.collapse");this.$element.trigger(a);if(!a.isDefaultPrevented()){if((a=this.$parent&&
this.$parent.find("> .panel > .in"))&&a.length){var c=a.data("bs.collapse");if(c&&c.transitioning)return;a.collapse("hide");c||a.data("bs.collapse",null)}var d=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[d](0);this.transitioning=1;a=function(){this.$element.removeClass("collapsing").addClass("collapse in")[d]("auto");this.transitioning=0;this.$element.trigger("shown.bs.collapse")};if(!b.support.transition)return a.call(this);c=b.camelCase(["scroll",d].join("-"));
this.$element.one(b.support.transition.end,b.proxy(a,this)).emulateTransitionEnd(350)[d](this.$element[0][c])}}};e.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var a=b.Event("hide.bs.collapse");this.$element.trigger(a);if(!a.isDefaultPrevented()){a=this.dimension();this.$element[a](this.$element[a]())[0].offsetHeight;this.$element.addClass("collapsing").removeClass("collapse").removeClass("in");this.transitioning=1;var c=function(){this.transitioning=0;this.$element.trigger("hidden.bs.collapse").removeClass("collapsing").addClass("collapse")};
if(!b.support.transition)return c.call(this);this.$element[a](0).one(b.support.transition.end,b.proxy(c,this)).emulateTransitionEnd(350)}}};e.prototype.toggle=function(){this[this.$element.hasClass("in")?"hide":"show"]()};var f=b.fn.collapse;b.fn.collapse=function(a){return this.each(function(){var c=b(this),d=c.data("bs.collapse"),g=b.extend({},e.DEFAULTS,c.data(),"object"==typeof a&&a);!d&&g.toggle&&"show"==a&&(a=!a);d||c.data("bs.collapse",d=new e(this,g));if("string"==typeof a)d[a]()})};b.fn.collapse.Constructor=
e;b.fn.collapse.noConflict=function(){b.fn.collapse=f;return this};b(document).on("click.bs.collapse.data-api","[data-toggle=collapse]",function(a){var c=b(this),d;a=c.attr("data-target")||a.preventDefault()||(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"");d=b(a);var g=(a=d.data("bs.collapse"))?"toggle":c.data(),e=c.attr("data-parent"),h=e&&b(e);a&&a.transitioning||(h&&h.find('[data-toggle=collapse][data-parent="'+e+'"]').not(c).addClass("collapsed"),c[d.hasClass("in")?"addClass":"removeClass"]("collapsed"));
d.collapse(g)})}(jQuery);
+function(b){function e(a){b(".dropdown-backdrop").remove();b("[data-toggle=dropdown]").each(function(){var d=f(b(this)),c={relatedTarget:this};d.hasClass("open")&&(d.trigger(a=b.Event("hide.bs.dropdown",c)),a.isDefaultPrevented()||d.removeClass("open").trigger("hidden.bs.dropdown",c))})}function f(a){var c=a.attr("data-target");c||(c=(c=a.attr("href"))&&/#[A-Za-z]/.test(c)&&c.replace(/.*(?=#[^\s]*$)/,""));return(c=c&&b(c))&&c.length?c:a.parent()}var a=function(a){b(a).on("click.bs.dropdown",this.toggle)};
a.prototype.toggle=function(a){var c=b(this);if(!c.is(".disabled, :disabled")){var d=f(c);a=d.hasClass("open");e();if(!a){if("ontouchstart"in document.documentElement&&!d.closest(".navbar-nav").length)b('<div class="dropdown-backdrop"/>').insertAfter(b(this)).on("click",e);var h={relatedTarget:this};d.trigger(a=b.Event("show.bs.dropdown",h));if(a.isDefaultPrevented())return;d.toggleClass("open").trigger("shown.bs.dropdown",h);c.focus()}return!1}};a.prototype.keydown=function(a){if(/(38|40|27)/.test(a.keyCode)){var c=
b(this);a.preventDefault();a.stopPropagation();if(!c.is(".disabled, :disabled")){var d=f(c),e=d.hasClass("open");if(!e||e&&27==a.keyCode)return 27==a.which&&d.find("[data-toggle=dropdown]").focus(),c.click();c=d.find("[role=menu] li:not(.divider):visible a, [role=listbox] li:not(.divider):visible a");c.length&&(d=c.index(c.filter(":focus")),38==a.keyCode&&0<d&&d--,40==a.keyCode&&d<c.length-1&&d++,~d||(d=0),c.eq(d).focus())}}};var c=b.fn.dropdown;b.fn.dropdown=function(c){return this.each(function(){var d=
b(this),e=d.data("bs.dropdown");e||d.data("bs.dropdown",e=new a(this));"string"==typeof c&&e[c].call(d)})};b.fn.dropdown.Constructor=a;b.fn.dropdown.noConflict=function(){b.fn.dropdown=c;return this};b(document).on("click.bs.dropdown.data-api",e).on("click.bs.dropdown.data-api",".dropdown form",function(a){a.stopPropagation()}).on("click.bs.dropdown.data-api","[data-toggle=dropdown]",a.prototype.toggle).on("keydown.bs.dropdown.data-api","[data-toggle=dropdown], [role=menu], [role=listbox]",a.prototype.keydown)}(jQuery);
+function(b){var e=function(a,c){this.options=c;this.$element=b(a);this.$backdrop=this.isShown=null;this.options.remote&&this.$element.find(".modal-content").load(this.options.remote,b.proxy(function(){this.$element.trigger("loaded.bs.modal")},this))};e.DEFAULTS={backdrop:!0,keyboard:!0,show:!0};e.prototype.toggle=function(a){return this[this.isShown?"hide":"show"](a)};e.prototype.show=function(a){var c=this,d=b.Event("show.bs.modal",{relatedTarget:a});this.$element.trigger(d);this.isShown||d.isDefaultPrevented()||
(this.isShown=!0,this.escape(),this.$element.on("click.dismiss.bs.modal",'[data-dismiss="modal"]',b.proxy(this.hide,this)),this.backdrop(function(){var d=b.support.transition&&c.$element.hasClass("fade");c.$element.parent().length||c.$element.appendTo(document.body);c.$element.show().scrollTop(0);d&&c.$element[0].offsetWidth;c.$element.addClass("in").attr("aria-hidden",!1);c.enforceFocus();var e=b.Event("shown.bs.modal",{relatedTarget:a});d?c.$element.find(".modal-dialog").one(b.support.transition.end,
function(){c.$element.focus().trigger(e)}).emulateTransitionEnd(300):c.$element.focus().trigger(e)}))};e.prototype.hide=function(a){a&&a.preventDefault();a=b.Event("hide.bs.modal");this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=!1,this.escape(),b(document).off("focusin.bs.modal"),this.$element.removeClass("in").attr("aria-hidden",!0).off("click.dismiss.bs.modal"),b.support.transition&&this.$element.hasClass("fade")?this.$element.one(b.support.transition.end,b.proxy(this.hideModal,
this)).emulateTransitionEnd(300):this.hideModal())};e.prototype.enforceFocus=function(){b(document).off("focusin.bs.modal").on("focusin.bs.modal",b.proxy(function(a){this.$element[0]===a.target||this.$element.has(a.target).length||this.$element.focus()},this))};e.prototype.escape=function(){if(this.isShown&&this.options.keyboard)this.$element.on("keyup.dismiss.bs.modal",b.proxy(function(a){27==a.which&&this.hide()},this));else this.isShown||this.$element.off("keyup.dismiss.bs.modal")};e.prototype.hideModal=
function(){var a=this;this.$element.hide();this.backdrop(function(){a.removeBackdrop();a.$element.trigger("hidden.bs.modal")})};e.prototype.removeBackdrop=function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};e.prototype.backdrop=function(a){var c=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var d=b.support.transition&&c;this.$backdrop=b('<div class="modal-backdrop '+c+'" />').appendTo(document.body);this.$element.on("click.dismiss.bs.modal",b.proxy(function(a){a.target===
a.currentTarget&&("static"==this.options.backdrop?this.$element[0].focus.call(this.$element[0]):this.hide.call(this))},this));d&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");a&&(d?this.$backdrop.one(b.support.transition.end,a).emulateTransitionEnd(150):a())}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(b.support.transition.end,a).emulateTransitionEnd(150):a()):a&&a()};var f=b.fn.modal;b.fn.modal=
function(a,c){return this.each(function(){var d=b(this),g=d.data("bs.modal"),f=b.extend({},e.DEFAULTS,d.data(),"object"==typeof a&&a);g||d.data("bs.modal",g=new e(this,f));if("string"==typeof a)g[a](c);else f.show&&g.show(c)})};b.fn.modal.Constructor=e;b.fn.modal.noConflict=function(){b.fn.modal=f;return this};b(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),d=c.attr("href"),e=b(c.attr("data-target")||d&&d.replace(/.*(?=#[^\s]+$)/,""));d=e.data("bs.modal")?
"toggle":b.extend({remote:!/#/.test(d)&&d},e.data(),c.data());c.is("a")&&a.preventDefault();e.modal(d,this).one("hide",function(){c.is(":visible")&&c.focus()})});b(document).on("show.bs.modal",".modal",function(){b(document.body).addClass("modal-open")}).on("hidden.bs.modal",".modal",function(){b(document.body).removeClass("modal-open")})}(jQuery);
+function(b){var e=function(a,c){this.type=this.options=this.enabled=this.timeout=this.hoverState=this.$element=null;this.init("tooltip",a,c)};e.DEFAULTS={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:!1,container:!1};e.prototype.init=function(a,c,d){this.enabled=!0;this.type=a;this.$element=b(c);this.options=this.getOptions(d);a=this.options.trigger.split(" ");
for(c=a.length;c--;)if(d=a[c],"click"==d)this.$element.on("click."+this.type,this.options.selector,b.proxy(this.toggle,this));else if("manual"!=d){var e="hover"==d?"mouseleave":"focusout";this.$element.on(("hover"==d?"mouseenter":"focusin")+"."+this.type,this.options.selector,b.proxy(this.enter,this));this.$element.on(e+"."+this.type,this.options.selector,b.proxy(this.leave,this))}this.options.selector?this._options=b.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};e.prototype.getDefaults=
function(){return e.DEFAULTS};e.prototype.getOptions=function(a){a=b.extend({},this.getDefaults(),this.$element.data(),a);a.delay&&"number"==typeof a.delay&&(a.delay={show:a.delay,hide:a.delay});return a};e.prototype.getDelegateOptions=function(){var a={},c=this.getDefaults();this._options&&b.each(this._options,function(b,e){c[b]!=e&&(a[b]=e)});return a};e.prototype.enter=function(a){var c=a instanceof this.constructor?a:b(a.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type);
clearTimeout(c.timeout);c.hoverState="in";if(!c.options.delay||!c.options.delay.show)return c.show();c.timeout=setTimeout(function(){"in"==c.hoverState&&c.show()},c.options.delay.show)};e.prototype.leave=function(a){var c=a instanceof this.constructor?a:b(a.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type);clearTimeout(c.timeout);c.hoverState="out";if(!c.options.delay||!c.options.delay.hide)return c.hide();c.timeout=setTimeout(function(){"out"==c.hoverState&&c.hide()},c.options.delay.hide)};
e.prototype.show=function(){var a=b.Event("show.bs."+this.type);if(this.hasContent()&&this.enabled&&(this.$element.trigger(a),!a.isDefaultPrevented())){var c=this;a=this.tip();this.setContent();this.options.animation&&a.addClass("fade");var d="function"==typeof this.options.placement?this.options.placement.call(this,a[0],this.$element[0]):this.options.placement,e=/\s?auto?\s?/i,f=e.test(d);f&&(d=d.replace(e,"")||"top");a.detach().css({top:0,left:0,display:"block"}).addClass(d);this.options.container?
a.appendTo(this.options.container):a.insertAfter(this.$element);e=this.getPosition();var h=a[0].offsetWidth,k=a[0].offsetHeight;if(f){var l=this.$element.parent();f=d;var n=document.documentElement.scrollTop||document.body.scrollTop,p="body"==this.options.container?window.innerWidth:l.outerWidth(),q="body"==this.options.container?window.innerHeight:l.outerHeight();l="body"==this.options.container?0:l.offset().left;d="bottom"==d&&e.top+e.height+k-n>q?"top":"top"==d&&0>e.top-n-k?"bottom":"right"==d&&
e.right+h>p?"left":"left"==d&&e.left-h<l?"right":d;a.removeClass(f).addClass(d)}e=this.getCalculatedOffset(d,e,h,k);this.applyPlacement(e,d);this.hoverState=null;d=function(){c.$element.trigger("shown.bs."+c.type)};b.support.transition&&this.$tip.hasClass("fade")?a.one(b.support.transition.end,d).emulateTransitionEnd(150):d()}};e.prototype.applyPlacement=function(a,c){var d=this.tip(),e=d[0].offsetWidth,f=d[0].offsetHeight,h=parseInt(d.css("margin-top"),10),k=parseInt(d.css("margin-left"),10);isNaN(h)&&
(h=0);isNaN(k)&&(k=0);a.top+=h;a.left+=k;b.offset.setOffset(d[0],b.extend({using:function(a){d.css({top:Math.round(a.top),left:Math.round(a.left)})}},a),0);d.addClass("in");h=d[0].offsetWidth;k=d[0].offsetHeight;if("top"==c&&k!=f){var l=!0;a.top=a.top+f-k}/bottom|top/.test(c)?(f=0,0>a.left&&(f=-2*a.left,a.left=0,d.offset(a),h=d[0].offsetWidth,k=d[0].offsetHeight),this.replaceArrow(f-e+h,h,"left")):this.replaceArrow(k-f,k,"top");l&&d.offset(a)};e.prototype.replaceArrow=function(a,c,b){this.arrow().css(b,
a?50*(1-a/c)+"%":"")};e.prototype.setContent=function(){var a=this.tip(),c=this.getTitle();a.find(".tooltip-inner")[this.options.html?"html":"text"](c);a.removeClass("fade in top bottom left right")};e.prototype.hide=function(){function a(){"in"!=c.hoverState&&d.detach();c.$element.trigger("hidden.bs."+c.type)}var c=this,d=this.tip(),e=b.Event("hide.bs."+this.type);this.$element.trigger(e);if(!e.isDefaultPrevented())return d.removeClass("in"),b.support.transition&&this.$tip.hasClass("fade")?d.one(b.support.transition.end,
a).emulateTransitionEnd(150):a(),this.hoverState=null,this};e.prototype.fixTitle=function(){var a=this.$element;(a.attr("title")||"string"!=typeof a.attr("data-original-title"))&&a.attr("data-original-title",a.attr("title")||"").attr("title","")};e.prototype.hasContent=function(){return this.getTitle()};e.prototype.getPosition=function(){var a=this.$element[0];return b.extend({},"function"==typeof a.getBoundingClientRect?a.getBoundingClientRect():{width:a.offsetWidth,height:a.offsetHeight},this.$element.offset())};
e.prototype.getCalculatedOffset=function(a,c,b,e){return"bottom"==a?{top:c.top+c.height,left:c.left+c.width/2-b/2}:"top"==a?{top:c.top-e,left:c.left+c.width/2-b/2}:"left"==a?{top:c.top+c.height/2-e/2,left:c.left-b}:{top:c.top+c.height/2-e/2,left:c.left+c.width}};e.prototype.getTitle=function(){var a=this.$element,b=this.options;return a.attr("data-original-title")||("function"==typeof b.title?b.title.call(a[0]):b.title)};e.prototype.tip=function(){return this.$tip=this.$tip||b(this.options.template)};
e.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")};e.prototype.validate=function(){this.$element[0].parentNode||(this.hide(),this.options=this.$element=null)};e.prototype.enable=function(){this.enabled=!0};e.prototype.disable=function(){this.enabled=!1};e.prototype.toggleEnabled=function(){this.enabled=!this.enabled};e.prototype.toggle=function(a){a=a?b(a.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type):this;a.tip().hasClass("in")?
a.leave(a):a.enter(a)};e.prototype.destroy=function(){clearTimeout(this.timeout);this.hide().$element.off("."+this.type).removeData("bs."+this.type)};var f=b.fn.tooltip;b.fn.tooltip=function(a){return this.each(function(){var c=b(this),d=c.data("bs.tooltip"),g="object"==typeof a&&a;if(d||"destroy"!=a)if(d||c.data("bs.tooltip",d=new e(this,g)),"string"==typeof a)d[a]()})};b.fn.tooltip.Constructor=e;b.fn.tooltip.noConflict=function(){b.fn.tooltip=f;return this}}(jQuery);
+function(b){var e=function(a,b){this.init("popover",a,b)};if(!b.fn.tooltip)throw Error("Popover requires tooltip.js");e.DEFAULTS=b.extend({},b.fn.tooltip.Constructor.DEFAULTS,{placement:"right",trigger:"click",content:"",template:'<div class="popover"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});e.prototype=b.extend({},b.fn.tooltip.Constructor.prototype);e.prototype.constructor=e;e.prototype.getDefaults=function(){return e.DEFAULTS};e.prototype.setContent=
function(){var a=this.tip(),b=this.getTitle(),d=this.getContent();a.find(".popover-title")[this.options.html?"html":"text"](b);a.find(".popover-content")[this.options.html?"string"==typeof d?"html":"append":"text"](d);a.removeClass("fade top bottom left right in");a.find(".popover-title").html()||a.find(".popover-title").hide()};e.prototype.hasContent=function(){return this.getTitle()||this.getContent()};e.prototype.getContent=function(){var a=this.$element,b=this.options;return a.attr("data-content")||
("function"==typeof b.content?b.content.call(a[0]):b.content)};e.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".arrow")};e.prototype.tip=function(){this.$tip||(this.$tip=b(this.options.template));return this.$tip};var f=b.fn.popover;b.fn.popover=function(a){return this.each(function(){var c=b(this),d=c.data("bs.popover"),g="object"==typeof a&&a;if(d||"destroy"!=a)if(d||c.data("bs.popover",d=new e(this,g)),"string"==typeof a)d[a]()})};b.fn.popover.Constructor=e;b.fn.popover.noConflict=
function(){b.fn.popover=f;return this}}(jQuery);
+function(b){function e(a,c){var d,g=b.proxy(this.process,this);this.$element=b(a).is("body")?b(window):b(a);this.$body=b("body");this.$scrollElement=this.$element.on("scroll.bs.scroll-spy.data-api",g);this.options=b.extend({},e.DEFAULTS,c);this.selector=(this.options.target||(d=b(a).attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"")||"")+" .nav li > a";this.offsets=b([]);this.targets=b([]);this.activeTarget=null;this.refresh();this.process()}e.DEFAULTS={offset:10};e.prototype.refresh=function(){var a=
this.$element[0]==window?"offset":"position";this.offsets=b([]);this.targets=b([]);var c=this;this.$body.find(this.selector).map(function(){var d=b(this);d=d.data("target")||d.attr("href");var e=/^#./.test(d)&&b(d);return e&&e.length&&e.is(":visible")&&[[e[a]().top+(!b.isWindow(c.$scrollElement.get(0))&&c.$scrollElement.scrollTop()),d]]||null}).sort(function(a,b){return a[0]-b[0]}).each(function(){c.offsets.push(this[0]);c.targets.push(this[1])})};e.prototype.process=function(){var a=this.$scrollElement.scrollTop()+
this.options.offset,b=(this.$scrollElement[0].scrollHeight||this.$body[0].scrollHeight)-this.$scrollElement.height(),d=this.offsets,e=this.targets,f=this.activeTarget,h;if(a>=b)return f!=(h=e.last()[0])&&this.activate(h);if(f&&a<=d[0])return f!=(h=e[0])&&this.activate(h);for(h=d.length;h--;)f!=e[h]&&a>=d[h]&&(!d[h+1]||a<=d[h+1])&&this.activate(e[h])};e.prototype.activate=function(a){this.activeTarget=a;b(this.selector).parentsUntil(this.options.target,".active").removeClass("active");a=b(this.selector+
'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parents("li").addClass("active");a.parent(".dropdown-menu").length&&(a=a.closest("li.dropdown").addClass("active"));a.trigger("activate.bs.scrollspy")};var f=b.fn.scrollspy;b.fn.scrollspy=function(a){return this.each(function(){var c=b(this),d=c.data("bs.scrollspy"),g="object"==typeof a&&a;d||c.data("bs.scrollspy",d=new e(this,g));if("string"==typeof a)d[a]()})};b.fn.scrollspy.Constructor=e;b.fn.scrollspy.noConflict=function(){b.fn.scrollspy=
f;return this};b(window).on("load",function(){b('[data-spy="scroll"]').each(function(){var a=b(this);a.scrollspy(a.data())})})}(jQuery);
+function(b){var e=function(a){this.element=b(a)};e.prototype.show=function(){var a=this.element,c=a.closest("ul:not(.dropdown-menu)"),d=a.data("target");d||(d=(d=a.attr("href"))&&d.replace(/.*(?=#[^\s]*$)/,""));if(!a.parent("li").hasClass("active")){var e=c.find(".active:last a")[0],f=b.Event("show.bs.tab",{relatedTarget:e});a.trigger(f);f.isDefaultPrevented()||(d=b(d),this.activate(a.parent("li"),c),this.activate(d,d.parent(),function(){a.trigger({type:"shown.bs.tab",relatedTarget:e})}))}};e.prototype.activate=
function(a,c,d){function e(){f.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");h?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");d&&d()}var f=c.find("> .active"),h=d&&b.support.transition&&f.hasClass("fade");h?f.one(b.support.transition.end,e).emulateTransitionEnd(150):e();f.removeClass("in")};var f=b.fn.tab;b.fn.tab=function(a){return this.each(function(){var c=b(this),
d=c.data("bs.tab");d||c.data("bs.tab",d=new e(this));if("string"==typeof a)d[a]()})};b.fn.tab.Constructor=e;b.fn.tab.noConflict=function(){b.fn.tab=f;return this};b(document).on("click.bs.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();b(this).tab("show")})}(jQuery);
+function(b){var e=function(a,c){this.options=b.extend({},e.DEFAULTS,c);this.$window=b(window).on("scroll.bs.affix.data-api",b.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",b.proxy(this.checkPositionWithEventLoop,this));this.$element=b(a);this.affixed=this.unpin=this.pinnedOffset=null;this.checkPosition()};e.RESET="affix affix-top affix-bottom";e.DEFAULTS={offset:0};e.prototype.getPinnedOffset=function(){if(this.pinnedOffset)return this.pinnedOffset;this.$element.removeClass(e.RESET).addClass("affix");
var a=this.$window.scrollTop();return this.pinnedOffset=this.$element.offset().top-a};e.prototype.checkPositionWithEventLoop=function(){setTimeout(b.proxy(this.checkPosition,this),1)};e.prototype.checkPosition=function(){if(this.$element.is(":visible")){var a=b(document).height(),c=this.$window.scrollTop(),d=this.$element.offset(),f=this.options.offset,m=f.top,h=f.bottom;"top"==this.affixed&&(d.top+=c);"object"!=typeof f&&(h=m=f);"function"==typeof m&&(m=f.top(this.$element));"function"==typeof h&&
(h=f.bottom(this.$element));c=null!=this.unpin&&c+this.unpin<=d.top?!1:null!=h&&d.top+this.$element.height()>=a-h?"bottom":null!=m&&c<=m?"top":!1;this.affixed!==c&&(this.unpin&&this.$element.css("top",""),d="affix"+(c?"-"+c:""),f=b.Event(d+".bs.affix"),this.$element.trigger(f),f.isDefaultPrevented()||(this.affixed=c,this.unpin="bottom"==c?this.getPinnedOffset():null,this.$element.removeClass(e.RESET).addClass(d).trigger(b.Event(d.replace("affix","affixed"))),"bottom"==c&&this.$element.offset({top:a-
h-this.$element.height()})))}};var f=b.fn.affix;b.fn.affix=function(a){return this.each(function(){var c=b(this),d=c.data("bs.affix"),f="object"==typeof a&&a;d||c.data("bs.affix",d=new e(this,f));if("string"==typeof a)d[a]()})};b.fn.affix.Constructor=e;b.fn.affix.noConflict=function(){b.fn.affix=f;return this};b(window).on("load",function(){b('[data-spy="affix"]').each(function(){var a=b(this),c=a.data();c.offset=c.offset||{};c.offsetBottom&&(c.offset.bottom=c.offsetBottom);c.offsetTop&&(c.offset.top=
c.offsetTop);a.affix(c)})})}(jQuery);